CREATE TABLE dataset_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(16) NOT NULL,
    label VARCHAR(32) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_dataset_version_code UNIQUE (code)
    );

CREATE TABLE item (
    id BIGINT Generated BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_version_id BIGINT NOT NULL,
    namespaced_id VARCHAR(64) NOT NULL,
    namespace VARCHAR(24) NOT NULL,
    path varchar(64) NOT NULL,
    display_name VARCHAR(80) NULL,
    raw_json JSONB NULL,

    CONSTRAINT fk_item_dataset_version FOREIGN KEY (dataset_version_id) REFERENCES dataset_version(id),

    CONSTRAINT uq_item_version_namespaced_id UNIQUE (dataset_version_id, namespaced_id)
);

CREATE TABLE pokemon (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_version_id BIGINT NOT NULL,
    slug varchar(50) NOT NULL,
    display_name VARCHAR(50) NOT NULL,
    national_dex_number smallint NOT NULL,
    generation_code VARCHAR(12) NOT NULL,
    implemented BOOLEAN NOT NULL DEFAULT TRUE,
    source_file VARCHAR(64) NOT NULL,
    raw_json JSONB NOT NULL,

    CONSTRAINT fk_pokemon_dataset_version FOREIGN KEY (dataset_version_id) REFERENCES dataset_version(id),
    CONSTRAINT uq_pokemon_version_slug UNIQUE (dataset_version_id, slug),
    CONSTRAINT uq_pokemon_version_dex UNIQUE (dataset_version_id, national_dex_number)
);

CREATE TABLE pokemon_form (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pokemon_id BIGINT NOT NULL,
    code VARCHAR(50) NOT NULL,
    display_name VARCHAR(80) NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    battle_only BOOLEAN NOT NULL DEFAULT FALSE,

    primary_type VARCHAR(16) NOT NULL,
    secondary_type VARCHAR(16) NULL,

    male_ratio NUMERIC(4,3) NULL,
    height_dm INTEGER NULL,
    weight_hg INTEGER NULL,

    catch_rate SMALLINT NULL,
    base_experience_yield SMALLINT NULL,
    experience_group VARCHAR(20) NULL,
    egg_cycles SMALLINT NULL,
    base_friendship SMALLINT NULL,
    base_scale NUMERIC(5,3) NULL,

    base_hp SMALLINT NOT NULL,
    base_attack SMALLINT NOT NULL,
    base_defense SMALLINT NOT NULL,
    base_special_attack SMALLINT NOT NULL,
    base_special_defense SMALLINT NOT NULL,
    base_speed SMALLINT NOT NULL,

    ev_hp SMALLINT NOT NULL DEFAULT 0,
    ev_attack SMALLINT NOT NULL DEFAULT 0,
    ev_defense SMALLINT NOT NULL DEFAULT 0,
    ev_special_attack SMALLINT NOT NULL DEFAULT 0,
    ev_special_defense SMALLINT NOT NULL DEFAULT 0,
    ev_speed SMALLINT NOT NULL DEFAULT 0,

    aspects_json JSONB NULL,
    labels_json JSONB NULL,
    raw_json JSONB NOT NULL,

    CONSTRAINT fk_pokemon_form_pokemon FOREIGN KEY (pokemon_id) REFERENCES pokemon(id),
    CONSTRAINT uq_pokemon_form_code UNIQUE (pokemon_id, code),
    CONSTRAINT ck_pokemon_form_male_ratio CHECK ( male_ratio IS NULL OR (male_ratio >= -1.00 AND male_ratio <= 1.00) ),
    CONSTRAINT ck_pokemon_form_base_stats CHECK (
        base_hp BETWEEN 1 AND 255
        AND base_attack BETWEEN 1 AND 255
        AND base_defense BETWEEN 1 AND 255
        AND base_special_attack BETWEEN 1 AND 255
        AND base_special_defense BETWEEN 1 AND 255
        AND base_speed BETWEEN 1 AND 255
        ),

    CONSTRAINT ck_pokemon_form_ev_stats
                          CHECK (
                              ev_hp BETWEEN 0 AND 3
                              AND ev_attack BETWEEN 0 AND 3
                              AND ev_defense BETWEEN 0 AND 3
                              AND ev_special_attack BETWEEN 0 AND 3
                              AND ev_special_defense BETWEEN 0 AND 3
                              AND ev_speed BETWEEN 0 AND 3
                              ),

    CONSTRAINT ck_pokemon_form_catch_rate
                          CHECK ( catch_rate IS NULL OR catch_rate BETWEEN 0 AND 255),

    CONSTRAINT ck_pokemon_form_base_friendship
                          CHECK ( base_friendship IS NULL OR base_friendship BETWEEN 0 AND 255)
);

CREATE TABLE pokemon_drop (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              pokemon_form_id BIGINT NOT NULL,
                              item_id BIGINT NOT NULL,

                              drop_pool_amount_min SMALLINT NULL,
                              drop_pool_amount_max SMALLINT NULL,

                              quantity_min SMALLINT NULL,
                              quantity_max SMALLINT NULL,

                              percentage NUMERIC(5,2) NULL,
                              raw_json JSONB NOT NULL,

                              CONSTRAINT fk_pokemon_drop_form
                                  FOREIGN KEY (pokemon_form_id) REFERENCES pokemon_form(id),

                              CONSTRAINT fk_pokemon_drop_item
                                  FOREIGN KEY (item_id) REFERENCES item(id),

                              CONSTRAINT ck_pokemon_drop_percentage
                                  CHECK (percentage IS NULL OR (percentage >= 0 AND percentage <= 100))
);

CREATE TABLE spawn_preset (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              dataset_version_id BIGINT NOT NULL,
                              code VARCHAR(50) NOT NULL,
                              source_file VARCHAR(64) NOT NULL,
                              condition_json JSONB NULL,
                              anticondition_json JSONB NULL,
                              raw_json JSONB NOT NULL,

                              CONSTRAINT fk_spawn_preset_dataset_version
                                  FOREIGN KEY (dataset_version_id) REFERENCES dataset_version(id),

                              CONSTRAINT uq_spawn_preset_version_code UNIQUE (dataset_version_id, code)
);

CREATE TABLE spawn_source_file (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   dataset_version_id BIGINT NOT NULL,
                                   filename VARCHAR(64) NOT NULL,
                                   comment_text TEXT NULL,
                                   enabled BOOLEAN NOT NULL DEFAULT TRUE,
                                   needed_installed_mods_json JSONB NULL,
                                   needed_uninstalled_mods_json JSONB NULL,
                                   raw_json JSONB NOT NULL,

                                   CONSTRAINT fk_spawn_source_file_dataset_version
                                       FOREIGN KEY (dataset_version_id) REFERENCES dataset_version(id),

                                   CONSTRAINT uq_spawn_source_file_version_filename UNIQUE (dataset_version_id, filename)
);

CREATE TABLE spawn_rule (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            spawn_source_file_id BIGINT NOT NULL,

                            external_id VARCHAR(40) NOT NULL,

                            pokemon_id BIGINT NOT NULL,
                            pokemon_form_id BIGINT NULL,

                            target_expression VARCHAR(120) NOT NULL,

                            spawn_type VARCHAR(20) NOT NULL,
                            spawnable_position_type VARCHAR(20) NOT NULL,
                            bucket VARCHAR(20) NOT NULL,

                            level_min SMALLINT NOT NULL,
                            level_max SMALLINT NOT NULL,

                            weight NUMERIC(8,3) NOT NULL,

                            max_herd_size SMALLINT NULL,
                            min_distance_between_spawns NUMERIC(6,2) NULL,

                            weight_multiplier_json JSONB NULL,
                            weight_multipliers_json JSONB NULL,
                            herdable_pokemon_json JSONB NULL,

                            raw_json JSONB NOT NULL,

                            CONSTRAINT fk_spawn_rule_source_file
                                FOREIGN KEY (spawn_source_file_id) REFERENCES spawn_source_file(id),

                            CONSTRAINT fk_spawn_rule_pokemon
                                FOREIGN KEY (pokemon_id) REFERENCES pokemon(id),

                            CONSTRAINT fk_spawn_rule_pokemon_form
                                FOREIGN KEY (pokemon_form_id) REFERENCES pokemon_form(id),

                            CONSTRAINT uq_spawn_rule_external_id_per_file UNIQUE (spawn_source_file_id, external_id),

                            CONSTRAINT ck_spawn_rule_spawn_type
                                CHECK (spawn_type IN ('pokemon', 'pokemon-herd')),

                            CONSTRAINT ck_spawn_rule_position_type
                                CHECK (spawnable_position_type IN ('grounded', 'surface', 'submerged', 'seafloor', 'fishing')),

                            CONSTRAINT ck_spawn_rule_bucket
                                CHECK (bucket IN ('common', 'uncommon', 'rare', 'ultra-rare')),

                            CONSTRAINT ck_spawn_rule_level
                                CHECK (level_min >= 1 AND level_max >= level_min),

                            CONSTRAINT ck_spawn_rule_weight
                                CHECK (weight > 0)
);

CREATE TABLE spawn_rule_preset (
                                   spawn_rule_id BIGINT NOT NULL,
                                   spawn_preset_id BIGINT NOT NULL,

                                   PRIMARY KEY (spawn_rule_id, spawn_preset_id),

                                   CONSTRAINT fk_spawn_rule_preset_rule
                                       FOREIGN KEY (spawn_rule_id) REFERENCES spawn_rule(id),

                                   CONSTRAINT fk_spawn_rule_preset_preset
                                       FOREIGN KEY (spawn_preset_id) REFERENCES spawn_preset(id)
);

CREATE TABLE spawn_condition (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 spawn_rule_id BIGINT NOT NULL,

                                 can_see_sky BOOLEAN NULL,
                                 is_raining BOOLEAN NULL,
                                 is_thundering BOOLEAN NULL,
                                 is_slime_chunk BOOLEAN NULL,

                                 min_x INTEGER NULL,
                                 max_x INTEGER NULL,
                                 min_y SMALLINT NULL,
                                 max_y SMALLINT NULL,

                                 min_light SMALLINT NULL,
                                 max_light SMALLINT NULL,
                                 min_sky_light SMALLINT NULL,
                                 max_sky_light SMALLINT NULL,

                                 min_lure_level SMALLINT NULL,
                                 max_lure_level SMALLINT NULL,

                                 moon_phase VARCHAR(16) NULL,
                                 time_range VARCHAR(16) NULL,
                                 rod_type VARCHAR(30) NULL,
                                 bait_item_expression VARCHAR(64) NULL,

                                 condition_json JSONB NULL,
                                 anticondition_json JSONB NULL,
                                 effective_condition_json JSONB NULL,
                                 effective_anticondition_json JSONB NULL,


                                 CONSTRAINT fk_spawn_condition_rule
                                     FOREIGN KEY (spawn_rule_id) REFERENCES spawn_rule(id),

                                 CONSTRAINT uq_spawn_condition_rule UNIQUE (spawn_rule_id),

                                 CONSTRAINT ck_spawn_condition_light
                                     CHECK (
                                         (min_light IS NULL OR min_light BETWEEN 0 AND 15)
                                             AND (max_light IS NULL OR max_light BETWEEN 0 AND 15)
                                             AND (min_sky_light IS NULL OR min_sky_light BETWEEN 0 AND 15)
                                             AND (max_sky_light IS NULL OR max_sky_light BETWEEN 0 AND 15)
                                         ),

                                 CONSTRAINT ck_spawn_condition_y
                                     CHECK (
                                         (min_y IS NULL OR min_y >= -512)
                                             AND (max_y IS NULL OR max_y <= 512)
                                         ),

                                CONSTRAINT ck_spawn_condition_x_order
                                     CHECK (min_x IS NULL OR max_x IS NULL OR min_x <= max_x),

                                 CONSTRAINT ck_spawn_condition_y_order
                                     CHECK (min_y IS NULL OR max_y IS NULL OR min_y <= max_y),

                                 CONSTRAINT ck_spawn_condition_light_order
                                     CHECK (min_light IS NULL OR max_light IS NULL OR min_light <= max_light),

                                 CONSTRAINT ck_spawn_condition_sky_light_order
                                     CHECK (min_sky_light IS NULL OR max_sky_light IS NULL OR min_sky_light <= max_sky_light),

                                 CONSTRAINT ck_spawn_condition_lure_order
                                     CHECK (min_lure_level IS NULL OR max_lure_level IS NULL OR min_lure_level <= max_lure_level)

);

CREATE TABLE spawn_condition_token (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       spawn_condition_id BIGINT NOT NULL,

                                       side VARCHAR(16) NOT NULL,
                                       token_type VARCHAR(24) NOT NULL,
                                       token_value VARCHAR(80) NOT NULL,
                                       is_tag BOOLEAN NOT NULL DEFAULT FALSE,

                                       CONSTRAINT fk_spawn_condition_token_condition
                                           FOREIGN KEY (spawn_condition_id) REFERENCES spawn_condition(id),

                                       CONSTRAINT ck_spawn_condition_token_side
                                           CHECK (side IN ('condition', 'anticondition')),

                                       CONSTRAINT ck_spawn_condition_token_type
                                           CHECK (token_type IN ('biome', 'structure', 'dimension', 'nearby_block', 'base_block', 'label'))
);

CREATE TABLE seasoning (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           item_id BIGINT NOT NULL,
                           colour VARCHAR(20) NOT NULL,
                           food_hunger SMALLINT NULL,
                           food_saturation NUMERIC(4,1) NULL,
                           raw_json JSONB NOT NULL,

                           CONSTRAINT fk_seasoning_item
                               FOREIGN KEY (item_id) REFERENCES item(id),

                           CONSTRAINT uq_seasoning_item UNIQUE (item_id)
);

CREATE TABLE seasoning_mob_effect (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      seasoning_id BIGINT NOT NULL,
                                      effect_id VARCHAR(40) NOT NULL,
                                      duration INTEGER NOT NULL,
                                      amplifier SMALLINT NOT NULL DEFAULT 0,
                                      ambient BOOLEAN NOT NULL DEFAULT FALSE,
                                      visible BOOLEAN NOT NULL DEFAULT TRUE,
                                      show_icon BOOLEAN NOT NULL DEFAULT TRUE,

                                      CONSTRAINT fk_seasoning_mob_effect_seasoning
                                          FOREIGN KEY (seasoning_id) REFERENCES seasoning(id)
);

CREATE TABLE bait_effect (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             item_id BIGINT NOT NULL,
                             effect_type VARCHAR(40) NOT NULL,
                             subcategory VARCHAR(40) NULL,
                             chance NUMERIC(4,2) NOT NULL,
                             value NUMERIC(8,4) NULL,
                             raw_json JSONB NOT NULL,

                             CONSTRAINT fk_bait_effect_item
                                 FOREIGN KEY (item_id) REFERENCES item(id),

                             CONSTRAINT ck_bait_effect_chance
                                 CHECK (chance >= 0 AND chance <= 1)
);

CREATE INDEX idx_pokemon_slug
    ON pokemon (slug);

CREATE INDEX idx_pokemon_dex
    ON pokemon (national_dex_number);

CREATE INDEX idx_pokemon_form_default
    ON pokemon_form (pokemon_id, is_default);

CREATE INDEX idx_spawn_rule_pokemon
    ON spawn_rule (pokemon_id);

CREATE INDEX idx_spawn_rule_form
    ON spawn_rule (pokemon_form_id);

CREATE INDEX idx_spawn_rule_bucket
    ON spawn_rule (bucket);

CREATE INDEX idx_spawn_rule_position_type
    ON spawn_rule (spawnable_position_type);

CREATE INDEX idx_spawn_condition_time_range
    ON spawn_condition (time_range);

CREATE INDEX idx_spawn_condition_moon_phase
    ON spawn_condition (moon_phase);

CREATE INDEX idx_spawn_condition_token_type_value
    ON spawn_condition_token (token_type, token_value);

CREATE INDEX idx_bait_effect_type_subcategory
    ON bait_effect (effect_type, subcategory);

CREATE INDEX idx_item_namespaced_id
    ON item (namespaced_id);

CREATE UNIQUE INDEX uq_pokemon_one_default_form
    ON pokemon_form (pokemon_id)
    WHERE is_default = TRUE;

CREATE INDEX idx_item_dataset_version_id
    ON item (dataset_version_id);

CREATE INDEX idx_pokemon_dataset_version_id
    ON pokemon (dataset_version_id);

CREATE INDEX idx_pokemon_form_pokemon_id
    ON pokemon_form (pokemon_id);

CREATE INDEX idx_pokemon_drop_form_id
    ON pokemon_drop (pokemon_form_id);

CREATE INDEX idx_pokemon_drop_item_id
    ON pokemon_drop (item_id);

CREATE INDEX idx_spawn_preset_dataset_version_id
    ON spawn_preset (dataset_version_id);

CREATE INDEX idx_spawn_source_file_dataset_version_id
    ON spawn_source_file (dataset_version_id);

CREATE INDEX idx_spawn_rule_source_file_id
    ON spawn_rule (spawn_source_file_id);

CREATE INDEX idx_spawn_condition_rule_id
    ON spawn_condition (spawn_rule_id);

CREATE INDEX idx_spawn_condition_token_condition_id
    ON spawn_condition_token (spawn_condition_id);

CREATE INDEX idx_spawn_rule_preset_preset_id
    ON spawn_rule_preset (spawn_preset_id);

CREATE INDEX idx_seasoning_item_id
    ON seasoning (item_id);

CREATE INDEX idx_seasoning_mob_effect_seasoning_id
    ON seasoning_mob_effect (seasoning_id);

CREATE INDEX idx_bait_effect_item_id
    ON bait_effect (item_id);

ALTER TABLE pokemon_form
    ADD CONSTRAINT uq_pokemon_form_id_pokemon
        UNIQUE (id, pokemon_id);

ALTER TABLE spawn_rule
    ADD CONSTRAINT fk_spawn_rule_form_matches_pokemon
        FOREIGN KEY (pokemon_form_id, pokemon_id)
            REFERENCES pokemon_form (id, pokemon_id);