CREATE TABLE translation (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key    VARCHAR(80)  NOT NULL,
    locale VARCHAR(5)   NOT NULL,
    value  VARCHAR(255) NOT NULL,
    CONSTRAINT uq_translation_key_locale UNIQUE (key, locale)
);

-- SpawnBucket
INSERT INTO translation (key, locale, value) VALUES
('bucket.COMMON',     'en', 'Common'),
('bucket.COMMON',     'fr', 'Commun'),
('bucket.UNCOMMON',   'en', 'Uncommon'),
('bucket.UNCOMMON',   'fr', 'Peu commun'),
('bucket.RARE',       'en', 'Rare'),
('bucket.RARE',       'fr', 'Rare'),
('bucket.ULTRA_RARE', 'en', 'Ultra Rare'),
('bucket.ULTRA_RARE', 'fr', 'Ultra Rare');

-- SpawnablePositionType
INSERT INTO translation (key, locale, value) VALUES
('position.GROUNDED',  'en', 'Ground'),
('position.GROUNDED',  'fr', 'Sol'),
('position.SURFACE',   'en', 'Surface'),
('position.SURFACE',   'fr', 'Surface'),
('position.SUBMERGED', 'en', 'Underwater'),
('position.SUBMERGED', 'fr', 'Sous l''eau'),
('position.SEAFLOOR',  'en', 'Seafloor'),
('position.SEAFLOOR',  'fr', 'Fond marin'),
('position.FISHING',   'en', 'Fishing'),
('position.FISHING',   'fr', 'Pêche');

-- SpawnType
INSERT INTO translation (key, locale, value) VALUES
('spawnType.POKEMON',       'en', 'Pokémon'),
('spawnType.POKEMON',       'fr', 'Pokémon'),
('spawnType.POKEMON_HERD',  'en', 'Pokémon Herd'),
('spawnType.POKEMON_HERD',  'fr', 'Troupeau de Pokémon');

-- SpawnConditionTokenType
INSERT INTO translation (key, locale, value) VALUES
('token.BIOME',        'en', 'Biome'),
('token.BIOME',        'fr', 'Biome'),
('token.STRUCTURE',    'en', 'Structure'),
('token.STRUCTURE',    'fr', 'Structure'),
('token.DIMENSION',    'en', 'Dimension'),
('token.DIMENSION',    'fr', 'Dimension'),
('token.NEARBY_BLOCK', 'en', 'Nearby block'),
('token.NEARBY_BLOCK', 'fr', 'Bloc proche'),
('token.BASE_BLOCK',   'en', 'Base block'),
('token.BASE_BLOCK',   'fr', 'Bloc de base'),
('token.LABEL',        'en', 'Label'),
('token.LABEL',        'fr', 'Label');