spring.datasource.url=jdbc:postgresql://localhost:5432/cobblemon?sslmode=disable
spring.datasource.username=cobblemon
spring.datasource.password=cobblemon
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-migration-naming=true
spring.main.web-application-type=none

logging.level.org.flywaydb=INFO
logging.level.be.loic.tfe_cobblemon=INFO
logging.level.be.loic.tfe_cobblemon.dataset.importer=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

app.dataset-import.code=cb161
app.dataset-import.label=Cobblemon 1.6.1
app.dataset-import.input-path=./import-data/cb161
app.dataset-import.clean-before-import=true

app.assets.path=./assets
app.assets.base-url=http://localhost:8080
