--
-- PostgreSQL database dump
--

\restrict GdLMaMcifdUbv5WOPlOk9HniQgcln7fkAyTSCRQUZOgfh3RxlR6phKWfuptBEut

-- Dumped from database version 18.3 (Ubuntu 18.3-1.pgdg22.04+1)
-- Dumped by pg_dump version 18.3 (Ubuntu 18.3-1.pgdg22.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO postgres;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: bait_effect; Type: TABLE; Schema: public; Owner: loic
--

CREATE TABLE public.bait_effect (
    id bigint NOT NULL,
    item_id bigint NOT NULL,
    effect_type character varying(40) NOT NULL,
    subcategory character varying(40),
    chance numeric(4,2) NOT NULL,
    value numeric(8,4),
    raw_json jsonb NOT NULL,
    CONSTRAINT ck_bait_effect_chance CHECK (((chance >= (0)::numeric) AND (chance <= (1)::numeric)))
);


ALTER TABLE public.bait_effect OWNER TO loic;

--
-- Name: bait_effect_id_seq; Type: SEQUENCE; Schema: public; Owner: loic
--

ALTER TABLE public.bait_effect ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bait_effect_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dataset_version; Type: TABLE; Schema: public; Owner: loic
--

CREATE TABLE public.dataset_version (
    id bigint NOT NULL,
    code character varying(16) NOT NULL,
    label character varying(32) NOT NULL,
    is_active boolean DEFAULT false NOT NULL,
    imported_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.dataset_version OWNER TO loic;

--
-- Name: dataset_version_id_seq; Type: SEQUENCE; Schema: public; Owner: loic
--

ALTER TABLE public.dataset_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dataset_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: loic
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


ALTER TABLE public.flyway_schema_history OWNER TO loic;

--
-- Name: item; Type: TABLE; Schema: public; Owner: loic
--

CREATE TABLE public.item (
    id bigint NOT NULL,
    dataset_version_id bigint NOT NULL,
    namespaced_id character varying(64) NOT NULL,
    namespace character varying(24) NOT NULL,
    path character varying(64) NOT NULL,
    display_name character varying(80),
    raw_json jsonb
);


ALTER TABLE public.item OWNER TO loic;

--
-- Name: item_id_seq; Type: SEQUENCE; Schema: public; Owner: loic
--

ALTER TABLE public.item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pokemon; Type: TABLE; Schema: public; Owner: loic
--

CREATE TABLE public.pokemon (
    id bigint NOT NULL,
    dataset_version_id bigint NOT NULL,
    slug character varying(50) NOT NULL,
    display_name character varying(50) NOT NULL,
    national_dex_number smallint NOT NULL,
    generation_code character varying(12) NOT NULL,
    implemented boolean DEFAULT true NOT NULL,
    source_file character varying(64) NOT NULL,
    raw_json jsonb NOT NULL
);


ALTER TABLE public.pokemon OWNER TO loic;

--
-- Name: pokemon_drop; Type: TABLE; Schema: public; Owner: loic
--

CREATE TABLE public.pokemon_drop (
    id bigint NOT NULL,
    pokemon_form_id bigint NOT NULL,
    item_id bigint NOT NULL,
    drop_pool_amount_min smallint,
    drop_pool_amount_max smallint,
    quantity_min smallint,
    quantity_max smallint,
    percentage numeric(5,2),
    raw_json jsonb NOT NULL,
    CONSTRAINT ck_pokemon_drop_percentage CHECK (((percentage IS NULL) OR ((percentage >= (0)::numeric) AND (percentage <= (100)::numeric))))
);


ALTER TABLE public.pokemon_drop OWNER TO loic;

--
-- Name: pokemon_drop_id_seq; Type: SEQUENCE; Schema: public; Owner: loic
--

ALTER TABLE public.pokemon_drop ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pokemon_drop_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pokemon_form; Type: TABLE; Schema: public; Owner: loic
--

CREATE TABLE public.pokemon_form (
    id bigint NOT NULL,
    pokemon_id bigint NOT NULL,
    code character varying(50) NOT NULL,
    display_name character varying(80) NOT NULL,
    is_default boolean DEFAULT false NOT NULL,
    battle_only boolean DEFAULT false NOT NULL,
    primary_type character varying(16) NOT NULL,
    secondary_type character varying(16),
    male_ratio numeric(4,3),
    height_dm integer,
    weight_hg integer,
    catch_rate smallint,
    base_experience_yield smallint,
    experience_group character varying(20),
    egg_cycles smallint,
    base_friendship smallint,
    base_scale numeric(5,3),
    base_hp smallint NOT NULL,
    base_attack smallint NOT NULL,
    base_defense smallint NOT NULL,
    base_special_attack smallint NOT NULL,
    base_special_defense smallint NOT NULL,
    base_speed smallint NOT NULL,
    ev_hp smallint DEFAULT 0 NOT NULL,
    ev_attack smallint DEFAULT 0 NOT NULL,
    ev_defense smallint DEFAULT 0 NOT NULL,
    ev_special_attack smallint DEFAULT 0 NOT NULL,
    ev_special_defense smallint DEFAULT 0 NOT NULL,
    ev_speed smallint DEFAULT 0 NOT NULL,
    aspects_json jsonb,
    labels_json jsonb,
    raw_json jsonb NOT NULL,
    CONSTRAINT ck_pokemon_form_base_friendship CHECK (((base_friendship IS NULL) OR ((base_friendship >= 0) AND (base_friendship <= 255)))),
    CONSTRAINT ck_pokemon_form_base_stats CHECK (((base_hp >= 1) AND (base_hp <= 255) AND ((base_attack >= 1) AND (base_attack <= 255)) AND ((base_defense >= 1) AND (base_defense <= 255)) AND ((base_special_attack >= 1) AND (base_special_attack <= 255)) AND ((base_special_defense >= 1) AND (base_special_defense <= 255)) AND ((base_speed >= 1) AND (base_speed <= 255)))),
    CONSTRAINT ck_pokemon_form_catch_rate CHECK (((catch_rate IS NULL) OR ((catch_rate >= 0) AND (catch_rate <= 255)))),
    CONSTRAINT ck_pokemon_form_ev_stats CHECK (((ev_hp >= 0) AND (ev_hp <= 3) AND ((ev_attack >= 0) AND (ev_attack <= 3)) AND ((ev_defense >= 0) AND (ev_defense <= 3)) AND ((ev_special_attack >= 0) AND (ev_special_attack <= 3)) AND ((ev_special_defense >= 0) AND (ev_special_defense <= 3)) AND ((ev_speed >= 0) AND (ev_speed <= 3)))),
    CONSTRAINT ck_pokemon_form_male_ratio CHECK (((male_ratio IS NULL) OR ((male_ratio >= '-1.00'::numeric) AND (male_ratio <= 1.00))))
);


ALTER TABLE public.pokemon_form OWNER TO loic;

--
-- Name: pokemon_form_id_seq; Type: SEQUENCE; Schema: public; Owner: loic
--

ALTER TABLE public.pokemon_form ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pokemon_form_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pokemon_id_seq; Type: SEQUENCE; Schema: public; Owner: loic
--

ALTER TABLE public.pokemon ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pokemon_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: seasoning; Type: TABLE; Schema: public; Owner: loic
--

CREATE TABLE public.seasoning (
    id bigint NOT NULL,
    item_id bigint NOT NULL,
    colour character varying(20) NOT NULL,
    food_hunger smallint,
    food_saturation numeric(4,1),
    raw_json jsonb NOT NULL
);


ALTER TABLE public.seasoning OWNER TO loic;

--
-- Name: seasoning_id_seq; Type: SEQUENCE; Schema: public; Owner: loic
--

ALTER TABLE public.seasoning ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seasoning_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: seasoning_mob_effect; Type: TABLE; Schema: public; Owner: loic
--

CREATE TABLE public.seasoning_mob_effect (
    id bigint NOT NULL,
    seasoning_id bigint NOT NULL,
    effect_id character varying(40) NOT NULL,
    duration integer NOT NULL,
    amplifier smallint DEFAULT 0 NOT NULL,
    ambient boolean DEFAULT false NOT NULL,
    visible boolean DEFAULT true NOT NULL,
    show_icon boolean DEFAULT true NOT NULL
);


ALTER TABLE public.seasoning_mob_effect OWNER TO loic;

--
-- Name: seasoning_mob_effect_id_seq; Type: SEQUENCE; Schema: public; Owner: loic
--

ALTER TABLE public.seasoning_mob_effect ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seasoning_mob_effect_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: spawn_condition; Type: TABLE; Schema: public; Owner: loic
--

CREATE TABLE public.spawn_condition (
    id bigint NOT NULL,
    spawn_rule_id bigint NOT NULL,
    can_see_sky boolean,
    is_raining boolean,
    is_thundering boolean,
    is_slime_chunk boolean,
    min_x integer,
    max_x integer,
    min_y smallint,
    max_y smallint,
    min_light smallint,
    max_light smallint,
    min_sky_light smallint,
    max_sky_light smallint,
    min_lure_level smallint,
    max_lure_level smallint,
    moon_phase character varying(16),
    time_range character varying(16),
    rod_type character varying(30),
    bait_item_expression character varying(64),
    condition_json jsonb,
    anticondition_json jsonb,
    effective_condition_json jsonb,
    effective_anticondition_json jsonb,
    CONSTRAINT ck_spawn_condition_light CHECK ((((min_light IS NULL) OR ((min_light >= 0) AND (min_light <= 15))) AND ((max_light IS NULL) OR ((max_light >= 0) AND (max_light <= 15))) AND ((min_sky_light IS NULL) OR ((min_sky_light >= 0) AND (min_sky_light <= 15))) AND ((max_sky_light IS NULL) OR ((max_sky_light >= 0) AND (max_sky_light <= 15))))),
    CONSTRAINT ck_spawn_condition_light_order CHECK (((min_light IS NULL) OR (max_light IS NULL) OR (min_light <= max_light))),
    CONSTRAINT ck_spawn_condition_lure_order CHECK (((min_lure_level IS NULL) OR (max_lure_level IS NULL) OR (min_lure_level <= max_lure_level))),
    CONSTRAINT ck_spawn_condition_sky_light_order CHECK (((min_sky_light IS NULL) OR (max_sky_light IS NULL) OR (min_sky_light <= max_sky_light))),
    CONSTRAINT ck_spawn_condition_x_order CHECK (((min_x IS NULL) OR (max_x IS NULL) OR (min_x <= max_x))),
    CONSTRAINT ck_spawn_condition_y CHECK ((((min_y IS NULL) OR (min_y >= '-512'::integer)) AND ((max_y IS NULL) OR (max_y <= 512)))),
    CONSTRAINT ck_spawn_condition_y_order CHECK (((min_y IS NULL) OR (max_y IS NULL) OR (min_y <= max_y)))
);


ALTER TABLE public.spawn_condition OWNER TO loic;

--
-- Name: spawn_condition_id_seq; Type: SEQUENCE; Schema: public; Owner: loic
--

ALTER TABLE public.spawn_condition ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.spawn_condition_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: spawn_condition_token; Type: TABLE; Schema: public; Owner: loic
--

CREATE TABLE public.spawn_condition_token (
    id bigint NOT NULL,
    spawn_condition_id bigint NOT NULL,
    side character varying(16) NOT NULL,
    token_type character varying(24) NOT NULL,
    token_value character varying(80) NOT NULL,
    is_tag boolean DEFAULT false NOT NULL,
    CONSTRAINT ck_spawn_condition_token_side CHECK (((side)::text = ANY (ARRAY[('condition'::character varying)::text, ('anticondition'::character varying)::text]))),
    CONSTRAINT ck_spawn_condition_token_type CHECK (((token_type)::text = ANY (ARRAY[('biome'::character varying)::text, ('structure'::character varying)::text, ('dimension'::character varying)::text, ('nearby_block'::character varying)::text, ('base_block'::character varying)::text, ('label'::character varying)::text])))
);


ALTER TABLE public.spawn_condition_token OWNER TO loic;

--
-- Name: spawn_condition_token_id_seq; Type: SEQUENCE; Schema: public; Owner: loic
--

ALTER TABLE public.spawn_condition_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.spawn_condition_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: spawn_preset; Type: TABLE; Schema: public; Owner: loic
--

CREATE TABLE public.spawn_preset (
    id bigint NOT NULL,
    dataset_version_id bigint NOT NULL,
    code character varying(50) NOT NULL,
    source_file character varying(64) NOT NULL,
    condition_json jsonb,
    anticondition_json jsonb,
    raw_json jsonb NOT NULL
);


ALTER TABLE public.spawn_preset OWNER TO loic;

--
-- Name: spawn_preset_id_seq; Type: SEQUENCE; Schema: public; Owner: loic
--

ALTER TABLE public.spawn_preset ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.spawn_preset_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: spawn_rule; Type: TABLE; Schema: public; Owner: loic
--

CREATE TABLE public.spawn_rule (
    id bigint NOT NULL,
    spawn_source_file_id bigint NOT NULL,
    external_id character varying(40) NOT NULL,
    pokemon_id bigint NOT NULL,
    pokemon_form_id bigint,
    target_expression character varying(120) NOT NULL,
    spawn_type character varying(20) NOT NULL,
    spawnable_position_type character varying(20) NOT NULL,
    bucket character varying(20) NOT NULL,
    level_min smallint NOT NULL,
    level_max smallint NOT NULL,
    weight numeric(8,3) NOT NULL,
    max_herd_size smallint,
    min_distance_between_spawns numeric(6,2),
    weight_multiplier_json jsonb,
    weight_multipliers_json jsonb,
    herdable_pokemon_json jsonb,
    raw_json jsonb NOT NULL,
    CONSTRAINT ck_spawn_rule_bucket CHECK (((bucket)::text = ANY (ARRAY[('common'::character varying)::text, ('uncommon'::character varying)::text, ('rare'::character varying)::text, ('ultra-rare'::character varying)::text]))),
    CONSTRAINT ck_spawn_rule_level CHECK (((level_min >= 1) AND (level_max >= level_min))),
    CONSTRAINT ck_spawn_rule_position_type CHECK (((spawnable_position_type)::text = ANY (ARRAY[('grounded'::character varying)::text, ('surface'::character varying)::text, ('submerged'::character varying)::text, ('seafloor'::character varying)::text, ('fishing'::character varying)::text]))),
    CONSTRAINT ck_spawn_rule_spawn_type CHECK (((spawn_type)::text = ANY (ARRAY[('pokemon'::character varying)::text, ('pokemon-herd'::character varying)::text]))),
    CONSTRAINT ck_spawn_rule_weight CHECK ((weight > (0)::numeric))
);


ALTER TABLE public.spawn_rule OWNER TO loic;

--
-- Name: spawn_rule_id_seq; Type: SEQUENCE; Schema: public; Owner: loic
--

ALTER TABLE public.spawn_rule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.spawn_rule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: spawn_rule_preset; Type: TABLE; Schema: public; Owner: loic
--

CREATE TABLE public.spawn_rule_preset (
    spawn_rule_id bigint NOT NULL,
    spawn_preset_id bigint NOT NULL
);


ALTER TABLE public.spawn_rule_preset OWNER TO loic;

--
-- Name: spawn_source_file; Type: TABLE; Schema: public; Owner: loic
--

CREATE TABLE public.spawn_source_file (
    id bigint NOT NULL,
    dataset_version_id bigint NOT NULL,
    filename character varying(64) NOT NULL,
    comment_text text,
    enabled boolean DEFAULT true NOT NULL,
    needed_installed_mods_json jsonb,
    needed_uninstalled_mods_json jsonb,
    raw_json jsonb NOT NULL
);


ALTER TABLE public.spawn_source_file OWNER TO loic;

--
-- Name: spawn_source_file_id_seq; Type: SEQUENCE; Schema: public; Owner: loic
--

ALTER TABLE public.spawn_source_file ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.spawn_source_file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: bait_effect; Type: TABLE DATA; Schema: public; Owner: loic
--

COPY public.bait_effect (id, item_id, effect_type, subcategory, chance, value, raw_json) FROM stdin;
\.


--
-- Data for Name: dataset_version; Type: TABLE DATA; Schema: public; Owner: loic
--

COPY public.dataset_version (id, code, label, is_active, imported_at) FROM stdin;
\.


--
-- Data for Name: flyway_schema_history; Type: TABLE DATA; Schema: public; Owner: loic
--

COPY public.flyway_schema_history (installed_rank, version, description, type, script, checksum, installed_by, installed_on, execution_time, success) FROM stdin;
1	1	init	SQL	V1__init.sql	1530397061	loic	2026-03-16 16:13:35.464737	95	t
\.


--
-- Data for Name: item; Type: TABLE DATA; Schema: public; Owner: loic
--

COPY public.item (id, dataset_version_id, namespaced_id, namespace, path, display_name, raw_json) FROM stdin;
\.


--
-- Data for Name: pokemon; Type: TABLE DATA; Schema: public; Owner: loic
--

COPY public.pokemon (id, dataset_version_id, slug, display_name, national_dex_number, generation_code, implemented, source_file, raw_json) FROM stdin;
\.


--
-- Data for Name: pokemon_drop; Type: TABLE DATA; Schema: public; Owner: loic
--

COPY public.pokemon_drop (id, pokemon_form_id, item_id, drop_pool_amount_min, drop_pool_amount_max, quantity_min, quantity_max, percentage, raw_json) FROM stdin;
\.


--
-- Data for Name: pokemon_form; Type: TABLE DATA; Schema: public; Owner: loic
--

COPY public.pokemon_form (id, pokemon_id, code, display_name, is_default, battle_only, primary_type, secondary_type, male_ratio, height_dm, weight_hg, catch_rate, base_experience_yield, experience_group, egg_cycles, base_friendship, base_scale, base_hp, base_attack, base_defense, base_special_attack, base_special_defense, base_speed, ev_hp, ev_attack, ev_defense, ev_special_attack, ev_special_defense, ev_speed, aspects_json, labels_json, raw_json) FROM stdin;
\.


--
-- Data for Name: seasoning; Type: TABLE DATA; Schema: public; Owner: loic
--

COPY public.seasoning (id, item_id, colour, food_hunger, food_saturation, raw_json) FROM stdin;
\.


--
-- Data for Name: seasoning_mob_effect; Type: TABLE DATA; Schema: public; Owner: loic
--

COPY public.seasoning_mob_effect (id, seasoning_id, effect_id, duration, amplifier, ambient, visible, show_icon) FROM stdin;
\.


--
-- Data for Name: spawn_condition; Type: TABLE DATA; Schema: public; Owner: loic
--

COPY public.spawn_condition (id, spawn_rule_id, can_see_sky, is_raining, is_thundering, is_slime_chunk, min_x, max_x, min_y, max_y, min_light, max_light, min_sky_light, max_sky_light, min_lure_level, max_lure_level, moon_phase, time_range, rod_type, bait_item_expression, condition_json, anticondition_json, effective_condition_json, effective_anticondition_json) FROM stdin;
\.


--
-- Data for Name: spawn_condition_token; Type: TABLE DATA; Schema: public; Owner: loic
--

COPY public.spawn_condition_token (id, spawn_condition_id, side, token_type, token_value, is_tag) FROM stdin;
\.


--
-- Data for Name: spawn_preset; Type: TABLE DATA; Schema: public; Owner: loic
--

COPY public.spawn_preset (id, dataset_version_id, code, source_file, condition_json, anticondition_json, raw_json) FROM stdin;
\.


--
-- Data for Name: spawn_rule; Type: TABLE DATA; Schema: public; Owner: loic
--

COPY public.spawn_rule (id, spawn_source_file_id, external_id, pokemon_id, pokemon_form_id, target_expression, spawn_type, spawnable_position_type, bucket, level_min, level_max, weight, max_herd_size, min_distance_between_spawns, weight_multiplier_json, weight_multipliers_json, herdable_pokemon_json, raw_json) FROM stdin;
\.


--
-- Data for Name: spawn_rule_preset; Type: TABLE DATA; Schema: public; Owner: loic
--

COPY public.spawn_rule_preset (spawn_rule_id, spawn_preset_id) FROM stdin;
\.


--
-- Data for Name: spawn_source_file; Type: TABLE DATA; Schema: public; Owner: loic
--

COPY public.spawn_source_file (id, dataset_version_id, filename, comment_text, enabled, needed_installed_mods_json, needed_uninstalled_mods_json, raw_json) FROM stdin;
\.


--
-- Name: bait_effect_id_seq; Type: SEQUENCE SET; Schema: public; Owner: loic
--

SELECT pg_catalog.setval('public.bait_effect_id_seq', 1, false);


--
-- Name: dataset_version_id_seq; Type: SEQUENCE SET; Schema: public; Owner: loic
--

SELECT pg_catalog.setval('public.dataset_version_id_seq', 1, false);


--
-- Name: item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: loic
--

SELECT pg_catalog.setval('public.item_id_seq', 1, false);


--
-- Name: pokemon_drop_id_seq; Type: SEQUENCE SET; Schema: public; Owner: loic
--

SELECT pg_catalog.setval('public.pokemon_drop_id_seq', 1, false);


--
-- Name: pokemon_form_id_seq; Type: SEQUENCE SET; Schema: public; Owner: loic
--

SELECT pg_catalog.setval('public.pokemon_form_id_seq', 1, false);


--
-- Name: pokemon_id_seq; Type: SEQUENCE SET; Schema: public; Owner: loic
--

SELECT pg_catalog.setval('public.pokemon_id_seq', 1, false);


--
-- Name: seasoning_id_seq; Type: SEQUENCE SET; Schema: public; Owner: loic
--

SELECT pg_catalog.setval('public.seasoning_id_seq', 1, false);


--
-- Name: seasoning_mob_effect_id_seq; Type: SEQUENCE SET; Schema: public; Owner: loic
--

SELECT pg_catalog.setval('public.seasoning_mob_effect_id_seq', 1, false);


--
-- Name: spawn_condition_id_seq; Type: SEQUENCE SET; Schema: public; Owner: loic
--

SELECT pg_catalog.setval('public.spawn_condition_id_seq', 1, false);


--
-- Name: spawn_condition_token_id_seq; Type: SEQUENCE SET; Schema: public; Owner: loic
--

SELECT pg_catalog.setval('public.spawn_condition_token_id_seq', 1, false);


--
-- Name: spawn_preset_id_seq; Type: SEQUENCE SET; Schema: public; Owner: loic
--

SELECT pg_catalog.setval('public.spawn_preset_id_seq', 1, false);


--
-- Name: spawn_rule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: loic
--

SELECT pg_catalog.setval('public.spawn_rule_id_seq', 1, false);


--
-- Name: spawn_source_file_id_seq; Type: SEQUENCE SET; Schema: public; Owner: loic
--

SELECT pg_catalog.setval('public.spawn_source_file_id_seq', 1, false);


--
-- Name: bait_effect bait_effect_pkey; Type: CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.bait_effect
    ADD CONSTRAINT bait_effect_pkey PRIMARY KEY (id);


--
-- Name: dataset_version dataset_version_pkey; Type: CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.dataset_version
    ADD CONSTRAINT dataset_version_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: item item_pkey; Type: CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.item
    ADD CONSTRAINT item_pkey PRIMARY KEY (id);


--
-- Name: pokemon_drop pokemon_drop_pkey; Type: CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.pokemon_drop
    ADD CONSTRAINT pokemon_drop_pkey PRIMARY KEY (id);


--
-- Name: pokemon_form pokemon_form_pkey; Type: CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.pokemon_form
    ADD CONSTRAINT pokemon_form_pkey PRIMARY KEY (id);


--
-- Name: pokemon pokemon_pkey; Type: CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.pokemon
    ADD CONSTRAINT pokemon_pkey PRIMARY KEY (id);


--
-- Name: seasoning_mob_effect seasoning_mob_effect_pkey; Type: CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.seasoning_mob_effect
    ADD CONSTRAINT seasoning_mob_effect_pkey PRIMARY KEY (id);


--
-- Name: seasoning seasoning_pkey; Type: CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.seasoning
    ADD CONSTRAINT seasoning_pkey PRIMARY KEY (id);


--
-- Name: spawn_condition spawn_condition_pkey; Type: CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.spawn_condition
    ADD CONSTRAINT spawn_condition_pkey PRIMARY KEY (id);


--
-- Name: spawn_condition_token spawn_condition_token_pkey; Type: CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.spawn_condition_token
    ADD CONSTRAINT spawn_condition_token_pkey PRIMARY KEY (id);


--
-- Name: spawn_preset spawn_preset_pkey; Type: CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.spawn_preset
    ADD CONSTRAINT spawn_preset_pkey PRIMARY KEY (id);


--
-- Name: spawn_rule spawn_rule_pkey; Type: CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.spawn_rule
    ADD CONSTRAINT spawn_rule_pkey PRIMARY KEY (id);


--
-- Name: spawn_rule_preset spawn_rule_preset_pkey; Type: CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.spawn_rule_preset
    ADD CONSTRAINT spawn_rule_preset_pkey PRIMARY KEY (spawn_rule_id, spawn_preset_id);


--
-- Name: spawn_source_file spawn_source_file_pkey; Type: CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.spawn_source_file
    ADD CONSTRAINT spawn_source_file_pkey PRIMARY KEY (id);


--
-- Name: dataset_version uq_dataset_version_code; Type: CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.dataset_version
    ADD CONSTRAINT uq_dataset_version_code UNIQUE (code);


--
-- Name: item uq_item_version_namespaced_id; Type: CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.item
    ADD CONSTRAINT uq_item_version_namespaced_id UNIQUE (dataset_version_id, namespaced_id);


--
-- Name: pokemon_form uq_pokemon_form_code; Type: CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.pokemon_form
    ADD CONSTRAINT uq_pokemon_form_code UNIQUE (pokemon_id, code);


--
-- Name: pokemon_form uq_pokemon_form_id_pokemon; Type: CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.pokemon_form
    ADD CONSTRAINT uq_pokemon_form_id_pokemon UNIQUE (id, pokemon_id);


--
-- Name: pokemon uq_pokemon_version_dex; Type: CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.pokemon
    ADD CONSTRAINT uq_pokemon_version_dex UNIQUE (dataset_version_id, national_dex_number);


--
-- Name: pokemon uq_pokemon_version_slug; Type: CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.pokemon
    ADD CONSTRAINT uq_pokemon_version_slug UNIQUE (dataset_version_id, slug);


--
-- Name: seasoning uq_seasoning_item; Type: CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.seasoning
    ADD CONSTRAINT uq_seasoning_item UNIQUE (item_id);


--
-- Name: spawn_condition uq_spawn_condition_rule; Type: CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.spawn_condition
    ADD CONSTRAINT uq_spawn_condition_rule UNIQUE (spawn_rule_id);


--
-- Name: spawn_preset uq_spawn_preset_version_code; Type: CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.spawn_preset
    ADD CONSTRAINT uq_spawn_preset_version_code UNIQUE (dataset_version_id, code);


--
-- Name: spawn_rule uq_spawn_rule_external_id_per_file; Type: CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.spawn_rule
    ADD CONSTRAINT uq_spawn_rule_external_id_per_file UNIQUE (spawn_source_file_id, external_id);


--
-- Name: spawn_source_file uq_spawn_source_file_version_filename; Type: CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.spawn_source_file
    ADD CONSTRAINT uq_spawn_source_file_version_filename UNIQUE (dataset_version_id, filename);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: loic
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: idx_bait_effect_item_id; Type: INDEX; Schema: public; Owner: loic
--

CREATE INDEX idx_bait_effect_item_id ON public.bait_effect USING btree (item_id);


--
-- Name: idx_bait_effect_type_subcategory; Type: INDEX; Schema: public; Owner: loic
--

CREATE INDEX idx_bait_effect_type_subcategory ON public.bait_effect USING btree (effect_type, subcategory);


--
-- Name: idx_item_dataset_version_id; Type: INDEX; Schema: public; Owner: loic
--

CREATE INDEX idx_item_dataset_version_id ON public.item USING btree (dataset_version_id);


--
-- Name: idx_item_namespaced_id; Type: INDEX; Schema: public; Owner: loic
--

CREATE INDEX idx_item_namespaced_id ON public.item USING btree (namespaced_id);


--
-- Name: idx_pokemon_dataset_version_id; Type: INDEX; Schema: public; Owner: loic
--

CREATE INDEX idx_pokemon_dataset_version_id ON public.pokemon USING btree (dataset_version_id);


--
-- Name: idx_pokemon_dex; Type: INDEX; Schema: public; Owner: loic
--

CREATE INDEX idx_pokemon_dex ON public.pokemon USING btree (national_dex_number);


--
-- Name: idx_pokemon_drop_form_id; Type: INDEX; Schema: public; Owner: loic
--

CREATE INDEX idx_pokemon_drop_form_id ON public.pokemon_drop USING btree (pokemon_form_id);


--
-- Name: idx_pokemon_drop_item_id; Type: INDEX; Schema: public; Owner: loic
--

CREATE INDEX idx_pokemon_drop_item_id ON public.pokemon_drop USING btree (item_id);


--
-- Name: idx_pokemon_form_default; Type: INDEX; Schema: public; Owner: loic
--

CREATE INDEX idx_pokemon_form_default ON public.pokemon_form USING btree (pokemon_id, is_default);


--
-- Name: idx_pokemon_form_pokemon_id; Type: INDEX; Schema: public; Owner: loic
--

CREATE INDEX idx_pokemon_form_pokemon_id ON public.pokemon_form USING btree (pokemon_id);


--
-- Name: idx_pokemon_slug; Type: INDEX; Schema: public; Owner: loic
--

CREATE INDEX idx_pokemon_slug ON public.pokemon USING btree (slug);


--
-- Name: idx_seasoning_item_id; Type: INDEX; Schema: public; Owner: loic
--

CREATE INDEX idx_seasoning_item_id ON public.seasoning USING btree (item_id);


--
-- Name: idx_seasoning_mob_effect_seasoning_id; Type: INDEX; Schema: public; Owner: loic
--

CREATE INDEX idx_seasoning_mob_effect_seasoning_id ON public.seasoning_mob_effect USING btree (seasoning_id);


--
-- Name: idx_spawn_condition_moon_phase; Type: INDEX; Schema: public; Owner: loic
--

CREATE INDEX idx_spawn_condition_moon_phase ON public.spawn_condition USING btree (moon_phase);


--
-- Name: idx_spawn_condition_rule_id; Type: INDEX; Schema: public; Owner: loic
--

CREATE INDEX idx_spawn_condition_rule_id ON public.spawn_condition USING btree (spawn_rule_id);


--
-- Name: idx_spawn_condition_time_range; Type: INDEX; Schema: public; Owner: loic
--

CREATE INDEX idx_spawn_condition_time_range ON public.spawn_condition USING btree (time_range);


--
-- Name: idx_spawn_condition_token_condition_id; Type: INDEX; Schema: public; Owner: loic
--

CREATE INDEX idx_spawn_condition_token_condition_id ON public.spawn_condition_token USING btree (spawn_condition_id);


--
-- Name: idx_spawn_condition_token_type_value; Type: INDEX; Schema: public; Owner: loic
--

CREATE INDEX idx_spawn_condition_token_type_value ON public.spawn_condition_token USING btree (token_type, token_value);


--
-- Name: idx_spawn_preset_dataset_version_id; Type: INDEX; Schema: public; Owner: loic
--

CREATE INDEX idx_spawn_preset_dataset_version_id ON public.spawn_preset USING btree (dataset_version_id);


--
-- Name: idx_spawn_rule_bucket; Type: INDEX; Schema: public; Owner: loic
--

CREATE INDEX idx_spawn_rule_bucket ON public.spawn_rule USING btree (bucket);


--
-- Name: idx_spawn_rule_form; Type: INDEX; Schema: public; Owner: loic
--

CREATE INDEX idx_spawn_rule_form ON public.spawn_rule USING btree (pokemon_form_id);


--
-- Name: idx_spawn_rule_pokemon; Type: INDEX; Schema: public; Owner: loic
--

CREATE INDEX idx_spawn_rule_pokemon ON public.spawn_rule USING btree (pokemon_id);


--
-- Name: idx_spawn_rule_position_type; Type: INDEX; Schema: public; Owner: loic
--

CREATE INDEX idx_spawn_rule_position_type ON public.spawn_rule USING btree (spawnable_position_type);


--
-- Name: idx_spawn_rule_preset_preset_id; Type: INDEX; Schema: public; Owner: loic
--

CREATE INDEX idx_spawn_rule_preset_preset_id ON public.spawn_rule_preset USING btree (spawn_preset_id);


--
-- Name: idx_spawn_rule_source_file_id; Type: INDEX; Schema: public; Owner: loic
--

CREATE INDEX idx_spawn_rule_source_file_id ON public.spawn_rule USING btree (spawn_source_file_id);


--
-- Name: idx_spawn_source_file_dataset_version_id; Type: INDEX; Schema: public; Owner: loic
--

CREATE INDEX idx_spawn_source_file_dataset_version_id ON public.spawn_source_file USING btree (dataset_version_id);


--
-- Name: uq_pokemon_one_default_form; Type: INDEX; Schema: public; Owner: loic
--

CREATE UNIQUE INDEX uq_pokemon_one_default_form ON public.pokemon_form USING btree (pokemon_id) WHERE (is_default = true);


--
-- Name: bait_effect fk_bait_effect_item; Type: FK CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.bait_effect
    ADD CONSTRAINT fk_bait_effect_item FOREIGN KEY (item_id) REFERENCES public.item(id);


--
-- Name: item fk_item_dataset_version; Type: FK CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.item
    ADD CONSTRAINT fk_item_dataset_version FOREIGN KEY (dataset_version_id) REFERENCES public.dataset_version(id);


--
-- Name: pokemon fk_pokemon_dataset_version; Type: FK CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.pokemon
    ADD CONSTRAINT fk_pokemon_dataset_version FOREIGN KEY (dataset_version_id) REFERENCES public.dataset_version(id);


--
-- Name: pokemon_drop fk_pokemon_drop_form; Type: FK CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.pokemon_drop
    ADD CONSTRAINT fk_pokemon_drop_form FOREIGN KEY (pokemon_form_id) REFERENCES public.pokemon_form(id);


--
-- Name: pokemon_drop fk_pokemon_drop_item; Type: FK CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.pokemon_drop
    ADD CONSTRAINT fk_pokemon_drop_item FOREIGN KEY (item_id) REFERENCES public.item(id);


--
-- Name: pokemon_form fk_pokemon_form_pokemon; Type: FK CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.pokemon_form
    ADD CONSTRAINT fk_pokemon_form_pokemon FOREIGN KEY (pokemon_id) REFERENCES public.pokemon(id);


--
-- Name: seasoning fk_seasoning_item; Type: FK CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.seasoning
    ADD CONSTRAINT fk_seasoning_item FOREIGN KEY (item_id) REFERENCES public.item(id);


--
-- Name: seasoning_mob_effect fk_seasoning_mob_effect_seasoning; Type: FK CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.seasoning_mob_effect
    ADD CONSTRAINT fk_seasoning_mob_effect_seasoning FOREIGN KEY (seasoning_id) REFERENCES public.seasoning(id);


--
-- Name: spawn_condition fk_spawn_condition_rule; Type: FK CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.spawn_condition
    ADD CONSTRAINT fk_spawn_condition_rule FOREIGN KEY (spawn_rule_id) REFERENCES public.spawn_rule(id);


--
-- Name: spawn_condition_token fk_spawn_condition_token_condition; Type: FK CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.spawn_condition_token
    ADD CONSTRAINT fk_spawn_condition_token_condition FOREIGN KEY (spawn_condition_id) REFERENCES public.spawn_condition(id);


--
-- Name: spawn_preset fk_spawn_preset_dataset_version; Type: FK CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.spawn_preset
    ADD CONSTRAINT fk_spawn_preset_dataset_version FOREIGN KEY (dataset_version_id) REFERENCES public.dataset_version(id);


--
-- Name: spawn_rule fk_spawn_rule_form_matches_pokemon; Type: FK CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.spawn_rule
    ADD CONSTRAINT fk_spawn_rule_form_matches_pokemon FOREIGN KEY (pokemon_form_id, pokemon_id) REFERENCES public.pokemon_form(id, pokemon_id);


--
-- Name: spawn_rule fk_spawn_rule_pokemon; Type: FK CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.spawn_rule
    ADD CONSTRAINT fk_spawn_rule_pokemon FOREIGN KEY (pokemon_id) REFERENCES public.pokemon(id);


--
-- Name: spawn_rule fk_spawn_rule_pokemon_form; Type: FK CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.spawn_rule
    ADD CONSTRAINT fk_spawn_rule_pokemon_form FOREIGN KEY (pokemon_form_id) REFERENCES public.pokemon_form(id);


--
-- Name: spawn_rule_preset fk_spawn_rule_preset_preset; Type: FK CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.spawn_rule_preset
    ADD CONSTRAINT fk_spawn_rule_preset_preset FOREIGN KEY (spawn_preset_id) REFERENCES public.spawn_preset(id);


--
-- Name: spawn_rule_preset fk_spawn_rule_preset_rule; Type: FK CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.spawn_rule_preset
    ADD CONSTRAINT fk_spawn_rule_preset_rule FOREIGN KEY (spawn_rule_id) REFERENCES public.spawn_rule(id);


--
-- Name: spawn_rule fk_spawn_rule_source_file; Type: FK CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.spawn_rule
    ADD CONSTRAINT fk_spawn_rule_source_file FOREIGN KEY (spawn_source_file_id) REFERENCES public.spawn_source_file(id);


--
-- Name: spawn_source_file fk_spawn_source_file_dataset_version; Type: FK CONSTRAINT; Schema: public; Owner: loic
--

ALTER TABLE ONLY public.spawn_source_file
    ADD CONSTRAINT fk_spawn_source_file_dataset_version FOREIGN KEY (dataset_version_id) REFERENCES public.dataset_version(id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--

\unrestrict GdLMaMcifdUbv5WOPlOk9HniQgcln7fkAyTSCRQUZOgfh3RxlR6phKWfuptBEut

