export const GENERATION_OPTIONS = [
    { value: '', label: 'Toutes générations' },
    { value: 'generation1', label: 'Génération I' },
    { value: 'generation2', label: 'Génération II' },
    { value: 'generation3', label: 'Génération III' },
    { value: 'generation4', label: 'Génération IV' },
    { value: 'generation5', label: 'Génération V' },
    { value: 'generation6', label: 'Génération VI' },
    { value: 'generation7', label: 'Génération VII' },
    { value: 'generation8', label: 'Génération VIII' },
    { value: 'generation9', label: 'Génération IX' },
] as const;

export const TYPE_COLORS: Record<string, string> = {
    normal:   'bg-gray-500',
    fire:     'bg-orange-500',
    water:    'bg-blue-500',
    grass:    'bg-green-500',
    electric: 'bg-yellow-400 text-gray-900',
    ice:      'bg-cyan-400 text-gray-900',
    fighting: 'bg-red-700',
    poison:   'bg-purple-500',
    ground:   'bg-yellow-600',
    flying:   'bg-indigo-400',
    psychic:  'bg-pink-500',
    bug:      'bg-lime-500 text-gray-900',
    rock:     'bg-yellow-700',
    ghost:    'bg-purple-800',
    dragon:   'bg-indigo-700',
    dark:     'bg-gray-800',
    steel:    'bg-gray-400 text-gray-900',
    fairy:    'bg-pink-300 text-gray-900',
};