spring.datasource.url=jdbc:postgresql://localhost:5432/cobblemon?sslmode=disable
spring.datasource.username=cobblemon
spring.datasource.password=cobblemon
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-migration-naming=true

logging.level.org.flywaydb=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.be.loic.tfe_cobblemon=TRACE
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

app.assets.path=./assets
app.assets.base-url=http://localhost:8080
